---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_6e836f0ca966
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mariadb://mariadb.default.svc.cluster.local:3306
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-cfg
                  key: CLIENT_ID
            - name: CLIENT_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-cfg
                  key: CLIENT_KEY
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/test
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
